CREATE TABLE MARCA (
    ID_MARCA int PRIMARY KEY AUTO_INCREMENT,
    DS_MARCA VARCHAR(50)
);

CREATE TABLE PRODUTO (
	ID_PRODUTO int PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO_PRODUTO VARCHAR(50),
	CODIGO_BARRAS VARCHAR(20)
);